#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/runtime.rs"));

#[repr(i32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum Status {
    Success = 0,
    GenericError = -1,
    ExplicitBoundsTooSmall = -2,
    BadType = -3,
    AccessOutOfBounds = -4,
    BufferAllocationTooLarge = -5,
    BufferExtentsTooLarge = -6,
    ConstraintsMakeRequiredRegionSmaller = -7,
    ConstraintViolated = -8,
    ParamTooSmall = -9,
    ParamTooLarge = -10,
    OutOfMemory = -11,
    BufferArgumentIsNull = -12,
    DebugToFileFailed = -13,
    CopyToHostFailed = -14,
    CopyToDeviceFailed = -15,
    DeviceMallocFailed = -16,
    DeviceSyncFailed = -17,
    DeviceFreeFailed = -18,
    NoDeviceInterface = -19,
    MatlabInitFailed = -20,
    MatlabBadParamType = -21,
    InternalError = -22,
    DeviceRunFailed = -23,
    UnalignedHostPtr = -24,
    BadFold = -25,
    FoldFactorTooSmall = -26,
    RequirementFailed = -27,
    BufferExtentsNegative = -28,
    Unused29 = -29,
    Unused30 = -30,
    SpecializeFail = -31,
    DeviceWrapNativeFailed = -32,
    DeviceDetachNativeFailed = -33,
    HostIsNull = -34,
    BadExternFold = -35,
    DeviceInterfaceNoDevice = -36,
    HostAndDeviceDirty = -37,
    BufferIsNull = -38,
    DeviceBufferCopyFailed = -39,
    DeviceCropUnsupported = -40,
    DeviceCropFailed = -41,
    IncompatibleDeviceInterface = -42,
    BadDimensions = -43,
    DeviceDirtyWithNoDeviceSupport = -44,
}
